[package]
name = "requests"
version = "1.0.0"
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
ntex = { version = "1.0.0", features = ["tokio"] }
futures = "0.3.1"
ntex-multipart = "0.4.0"
