[package]
name = "server"
version = "1.0.0"
workspace = "../"
edition = "2018"

[dependencies]
ntex = { version = "1.0.0", features = ["tokio", "openssl"] }
futures = "0.3"
openssl = { version = "0.10", features = ["vendored"] }
tokio = { version = "1.16.1", features = ["full"] }
