[package]
name = "databases"
version = "1.0.0"
edition = "2018"

[dependencies]
ntex = { version = "0.7", features = ["tokio"] }
diesel = { version = "2", features = ["sqlite", "r2d2"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }
