name: Check examples

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  check-examples:
    name: Check examples
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -A dead-code -A unused-variables

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1.6
      - name: test examples
        run: |
          cd examples
          cargo test
